### PR TITLE
Add mongoose support to api

### PR DESCRIPTION
**Pull request by luqezman**
## Status
**READY**

## Migrations
NO

## Description
Add mongoose support to api

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Steps to Test or Reproduce

Before you start, make sure you have:

1. yarn dependencies installed
2. nx installed globally
3. docker running

```sh
# Starting docker
docker-compose up -t

# Starting api
nx serve api
```

Make sure the last log message contains `Listening at http://localhost:3333/api` after running the api

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by felinto-dev — COMMENTED** [review]
Good job. 

I think that you could add a health check. It's not hard.
https://github.com/kubeapps/chartsvc/blob/master/docker-compose.yml

It's not necessary to expose port 27017, it can generate issues if you already Mongo installed. I suggest you use Mongo Express, and expose port 80.
https://hub.docker.com/_/mongo-express

**Review by felinto-dev — COMMENTED** [review]
Why you don't use @nestjs/config?

In the development environment, I think that it's ok created a file ".env.development". Add this file to .gitignore. You can make a reference for this file using docker-compose.

https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

The great advantage is that you will manage the settings for docker-compose and your API in one place.

**Review by felinto-dev — CHANGES_REQUESTED** [review]
Why you don't use @nestjs/config?

In the development environment, I think that it's ok created a file ".env.development". Add this file to .gitignore. You can make a reference for this file using docker-compose.

https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

The great advantage is that you will manage the settings for docker-compose and your API in one place.

**Comment by felinto-dev** [comment]
> ```shell
> # Starting docker
> docker-compose up -t
> 
> # Starting api
> nx serve api
> ```

I think that you would say "npx serve api", right?

**Comment by luqezman** [comment]
> > ```shell
> > # Starting docker
> > docker-compose up -t
> > 
> > # Starting api
> > nx serve api
> > ```
> 
> I think that you would say "npx serve api", right?

Im using https://nx.dev, so `nx` is correct

**Comment by luqezman** [comment]
> Why you don't use @nestjs/config?
> 
> In the development environment, I think that it's ok created a file ".env.development". Add this file to .gitignore. You can make a reference for this file using docker-compose.
> 
> https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option
> 
> The great advantage is that you will manage the settings for docker-compose and your API in one place.

@felinto-dev I'll decide later if I use @nestjs/config or the nx.dev environments system itself.

**Comment by luqezman** [comment]
> [I don't have any idea how to delete this comment]

@felinto-dev np :)

**Comment by luqezman** [comment]
> Good job.
> 
> I think that you could add a health check. It's not hard.
> https://github.com/kubeapps/chartsvc/blob/master/docker-compose.yml
> 
> It's not necessary to expose port 27017, it can generate issues if you already Mongo installed. I suggest you use Mongo Express, and expose port 80.
> https://hub.docker.com/_/mongo-express

@felinto-dev good point, I'll do it.

**Review by felinto-dev — APPROVED** [review]

**Pull request merged**
